//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstallPad.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstallPad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about_logo {
            get {
                object obj = ResourceManager.GetObject("about_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlternateDownloadLocation.
        /// </summary>
        internal static string AlternateDownloadLocation {
            get {
                return ResourceManager.GetString("AlternateDownloadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlternateFileUrl.
        /// </summary>
        internal static string AlternateFileUrl {
            get {
                return ResourceManager.GetString("AlternateFileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find an application file. Ensure that there is an applist.xml file in the same folder as InstallPad.exe.
        /// </summary>
        internal static string AppFileNotFound {
            get {
                return ResourceManager.GetString("AppFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing the application file. The file contains invalid XML..
        /// </summary>
        internal static string AppFileParseError {
            get {
                return ResourceManager.GetString("AppFileParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationList.
        /// </summary>
        internal static string ApplicationList {
            get {
                return ResourceManager.GetString("ApplicationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppListFile.
        /// </summary>
        internal static string AppListFile {
            get {
                return ResourceManager.GetString("AppListFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save an application list without a filename..
        /// </summary>
        internal static string AppListMissingFilename {
            get {
                return ResourceManager.GetString("AppListMissingFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized element in an application.
        /// </summary>
        internal static string AppListUnknownElement {
            get {
                return ResourceManager.GetString("AppListUnknownElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized application option.
        /// </summary>
        internal static string AppListXmlUnknown {
            get {
                return ResourceManager.GetString("AppListXmlUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open new application list.
        /// </summary>
        internal static string AppLocked {
            get {
                return ResourceManager.GetString("AppLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open a new application list while an program is downloading or installing..
        /// </summary>
        internal static string AppLockedShort {
            get {
                return ResourceManager.GetString("AppLockedShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to found but not found.
        /// </summary>
        internal static string AppVersionNotFound {
            get {
                return ResourceManager.GetString("AppVersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized proxy option.
        /// </summary>
        internal static string BadProxyOption {
            get {
                return ResourceManager.GetString("BadProxyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string BooleanFalse {
            get {
                return ResourceManager.GetString("BooleanFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        internal static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckedByDefault.
        /// </summary>
        internal static string CheckedByDefault {
            get {
                return ResourceManager.GetString("CheckedByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closeOver {
            get {
                object obj = ResourceManager.GetObject("closeOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closePressed {
            get {
                object obj = ResourceManager.GetObject("closePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page . . ..
        /// </summary>
        internal static string DefaultHomePageCaption {
            get {
                return ResourceManager.GetString("DefaultHomePageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayName.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayVersion.
        /// </summary>
        internal static string DisplayVersion {
            get {
                return ResourceManager.GetString("DisplayVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownloadLatestVersion.
        /// </summary>
        internal static string DownloadLatestVersion {
            get {
                return ResourceManager.GetString("DownloadLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownloadTo.
        /// </summary>
        internal static string DownloadTo {
            get {
                return ResourceManager.GetString("DownloadTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Application.
        /// </summary>
        internal static string EditApplication {
            get {
                return ResourceManager.GetString("EditApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating install folder.
        /// </summary>
        internal static string Errorcreatinginstallfolder {
            get {
                return ResourceManager.GetString("Errorcreatinginstallfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were errors while downloading..
        /// </summary>
        internal static string ErrorDownloading {
            get {
                return ResourceManager.GetString("ErrorDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were errors while installing..
        /// </summary>
        internal static string ErrorInstalling {
            get {
                return ResourceManager.GetString("ErrorInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileUrl.
        /// </summary>
        internal static string FileUrl {
            get {
                return ResourceManager.GetString("FileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        internal static string HomePageCaption {
            get {
                return ResourceManager.GetString("HomePageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomePageUrl.
        /// </summary>
        internal static string HomePageUrl {
            get {
                return ResourceManager.GetString("HomePageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstallationOptions.
        /// </summary>
        internal static string InstallationOptions {
            get {
                return ResourceManager.GetString("InstallationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstallationRoot.
        /// </summary>
        internal static string InstallationRoot {
            get {
                return ResourceManager.GetString("InstallationRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstallerArguments.
        /// </summary>
        internal static string InstallerArguments {
            get {
                return ResourceManager.GetString("InstallerArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating install folder.
        /// </summary>
        internal static string InstallFolderCreateError {
            get {
                return ResourceManager.GetString("InstallFolderCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstallInOrder.
        /// </summary>
        internal static string InstallInOrder {
            get {
                return ResourceManager.GetString("InstallInOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstallPad.
        /// </summary>
        internal static string InstallPad {
            get {
                return ResourceManager.GetString("InstallPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phil Crosby (phil.crosby@gmail.com).
        /// </summary>
        internal static string InstallPadAuthor {
            get {
                return ResourceManager.GetString("InstallPadAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zac Ruiz (zac.ruiz@gmail.com).
        /// </summary>
        internal static string InstallPadContrib1 {
            get {
                return ResourceManager.GetString("InstallPadContrib1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2006 Phil Crosby.
        /// </summary>
        internal static string InstallPadCopyRight {
            get {
                return ResourceManager.GetString("InstallPadCopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get programs faster.
        /// </summary>
        internal static string InstallPadSlogan {
            get {
                return ResourceManager.GetString("InstallPadSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.installpad.com.
        /// </summary>
        internal static string InstallPadUrl {
            get {
                return ResourceManager.GetString("InstallPadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.4.
        /// </summary>
        internal static string InstallPadVersion {
            get {
                return ResourceManager.GetString("InstallPadVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid namespace..
        /// </summary>
        internal static string InvalidNamespace {
            get {
                return ResourceManager.GetString("InvalidNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This license governs use of the accompanying software. If you use the software, you accept this license. If you do not accept the license, do not use the software.
        ///
        ///1. Definitions
        ///The terms &quot;reproduce,&quot; &quot;reproduction&quot; and &quot;distribution&quot; have the same meaning here as under U.S. copyright law.
        ///&quot;You&quot; means the licensee of the software.
        ///&quot;Your company&quot; means the company you worked for when you downloaded the software.
        ///&quot;Personal use&quot; means use not within your company, and specifically excludes the right to  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logoBorder {
            get {
                object obj = ResourceManager.GetObject("logoBorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostInstallScript.
        /// </summary>
        internal static string PostInstallScript {
            get {
                return ResourceManager.GetString("PostInstallScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        internal static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SilentInstall.
        /// </summary>
        internal static string SilentInstall {
            get {
                return ResourceManager.GetString("SilentInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimultaneousDownloads.
        /// </summary>
        internal static string SimultaneousDownloads {
            get {
                return ResourceManager.GetString("SimultaneousDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating temporary folder for downloaded files: .
        /// </summary>
        internal static string TempFileCreateError {
            get {
                return ResourceManager.GetString("TempFileCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to find the full path of either your temp folder or your program files folder. This might be due to some bad environment variables..
        /// </summary>
        internal static string TempFileNotFound {
            get {
                return ResourceManager.GetString("TempFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details..
        /// </summary>
        internal static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
    }
}
